# config.yaml
---
data_quality_checks:
  workspace.default.source_table_perfect:
    uniqueness: 
      - customer_id
      - order_id
    completeness:
      - order_id
      - order_date
    validity:
      - column: order_date
        check: "order_date > '2023-01-01'"
    row_count:
      min: 10
      max: 100000
  workspace.default.source_table_uniqueness_fail:
    uniqueness:
      - customer_id
      - order_id
    completeness:
      - order_id
      - order_date
    validity:
      - column: order_date
        check: "order_date >= '2024-01-01'"
    row_count:
      min: 5
      max: 10
  workspace.default.source_table_completeness_validity_fail:
    uniqueness:
      - customer_id
      - order_id
    completeness:
      - order_id
      - order_date
    validity:
      - column: order_date
        check: "order_date >= '2024-01-01'"
    row_count:
      min: 5
      max: 10
  workspace.default.source_table_row_count_fail:
    uniqueness:
      - customer_id
      - order_id
    completeness:
      - order_id
      - order_date
    validity:
      - column: order_date
        check: "order_date >= '2024-01-01'"
    row_count:
      min: 1000
      max: 100000